__title__ = 'dfainductor'
__description__ = 'A python tool for solving minDFA problem.'
__version__ = '0.1.0'
__author__ = 'Ilya Zakirzyanov'
__author_email__ = 'ilya.zakirzyanov@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2020 Ilya Zakirzyanov'
